### ISSUE TITLE
Add instructions on how this repo can be used

### ISSUE THREAD

**Issue by Marenz** [frequenz-floss/frequenz-api-dispatch#36]
### What's needed?

Looking at this repo, I have not the slightest idea how it is supposed to be used.
I found no examples, no python files and no explanations on how the .proto definitions would end up being used in actual
python code.

**Comment by llucax** [comment]
This package is not intended to be used directly by users, we need to implement a dispatch API client on top of it (like we have a [microgrid API client](https://github.com/frequenz-floss/frequenz-sdk-python/tree/v0.x.x/src/frequenz/sdk/microgrid/client)) and even then very few users are probably going to use the API client directly, the idea is to have an actor and a high-level interface to take care of all the details.

The high-level interface is envisioned to work something like this:

```py
async def run():
    # Receives a dispatch object each time a dispatch is created or modified
    dispatch_arrived = dispatch_helper.new_arrived_receiver()

    # Receives a dispatch object each time the dispatch is scheduled to start
    dispatch_ready = dispatch_helper.new_ready_receiver()
    
    async for selected in select(dispatch_ready, dispatch_arrived):
        if is_selected(selected, dispatch_ready):
            match dispatch.type:
                case DISPATCH_TYPE_BATTERY_CHARGE:
                    battery_pool = microgrid.battery_pool(dispatch.battery_set, task_id)
                    battery_pool.set_charge(dispatch.power)
                ...
        elif is_selected(selected, dispatch_arrived):
            log.info("New dispatch arrived %s", dispatch)
```

That said, I'm leaving this issue opened because at some point we need to have better documentation, it is just very low priority at this point.
